apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-hello
  labels:
    app: fastapi-hello
spec:
  replicas: 4
  selector:
    matchLabels:
      app: fastapi-hello
  template:
    metadata:
      labels:
        app: fastapi-hello
    spec:
      containers:
        - name: fastapi-hello
          image: rizwandevops/argocd:latest
          ports:
            - containerPort: 8000
